### ISSUE TITLE
Error when audit.net tries to audit nuget packages

### ISSUE THREAD

**Issue by eloisetaylor5693** [OSSIndex/audit.net#22] opened 2019-02-18 16:31 UTC
Whether running manually, or automatically, audit.net errors with message "Object reference not set to an instance of an object." in the output log in Visual Studio.

## **Visual Studio info**

> Microsoft Visual Studio Professional 2017 
> Version 15.8.2
> VisualStudio.15.Release/15.8.2+28010.2016
> Microsoft .NET Framework
> Version 4.7.02558
> 
> Installed Version: Professional
> 
> NuGet Package Manager   4.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> OSSAuditPackage Extension   1.1
> OSSAuditPackage Visual Studio Extension Detailed Info

## **Error**
```
Finding dependencies...
  Fetch dependencies for pkg:nuget/SpecFlow.NUnit@1.1.1
An error occurred while trying to audit package(s): Object reference not set to an instance of an object.

An error occurred while trying to audit package(s):    at NugetAuditor.Lib.NugetAuditor.getDependencies(PackageId pkg)
   at NugetAuditor.Lib.NugetAuditor.getDependencies(IEnumerable`1 packages, ILogger logger)
   at NugetAuditor.Lib.NugetAuditor.<AuditPackagesImpl>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NugetAuditor.Lib.NugetAuditor.AuditPackages(IEnumerable`1 packages, Int32 cacheSync, ILogger logger)
   at NugetAuditor.VSIX.NugetAuditManager.<>c__DisplayClass41_0.<RunAudit>b__0(Object state) in D:\git.vor\audit.net\src\NugetAuditor\NugetAuditor.VSIX\NugetAuditManager.cs:line 470

```

**Comment by ken-duck** [comment] 2019-02-19 03:52
Whoops. Thanks for letting us know.

**Comment by eloisetaylor5693** [comment] 2019-02-19 10:57
I found it also stops you from being able to do Nuget package restore as well :(

**Comment by allisterb** [comment] 2019-02-26 02:57
@ken-duck I think I located the source of initial null reference error, but there is now a JSON error when deserializing records from the OSS Index server:

```
An error occurred while trying to audit package(s):    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at NugetAuditor.Lib.OSSIndex.ApiClient.SearchPackages(IEnumerable`1 inCoords)
   at NugetAuditor.Lib.NugetAuditor.<AuditPackagesImpl>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NugetAuditor.Lib.NugetAuditor.AuditPackages(IEnumerable`1 packages, Int32 cacheSync, ILogger logger)
   at NugetAuditor.VSIX.NugetAuditManager.<>c__DisplayClass41_0.<RunAudit>b__0(Object state) in C:\Projects\audit.net\src\NugetAuditor\NugetAuditor.VSIX\NugetAuditManager 
```

It's probably a missing object in the JSON response.

**Comment by allisterb** [comment] 2019-02-26 04:34
@eloisetaylor5693 Sorry for taking so long to respond to this. Could you try installing the version attached and see if the problem is resolved.
[NugetAuditor.VSIX.zip](https://github.com/OSSIndex/audit.net/files/2903797/NugetAuditor.VSIX.zip)

**Comment by OSSIndex-Admin** [comment] 2019-03-06 17:55
I reproduced the error on my machine, and the provided archive appears to resolve the issue.

I will be shortly performing a release and then will close this ticket.

I did notice some logging messages which I believe should be hidden. Issue raised: https://github.com/OSSIndex/DevAudit/issues/102

**Comment by ken-duck** [comment] 2019-03-10 00:51
A new version (3.0.3) has been uploaded to the marketplace and should be through validation soon. It has fixes for this problem, and works on our local installation which reproduced the error.

If the problem persists for you, please let us know and we will dig further.

**Comment by ken-duck** [comment] 2019-03-10 00:51
Thank you for your report and your patience.

**Closed by ken-duck** 2019-03-10 00:51 UTC
